image: centos:v9

variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_COMMIT_SHORT_SHA/yig

before_script:
  - ip a
  - docker version
  - pwd

stages:
  - build
  - create_rpm

build_yig:
  stage: build
  script:
    - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
    - pwd
    - make build_internal
    - make env
    - make run
    - chmod 644 go.mod go.sum
    - python test/sanity.py
    - pushd test/go
    - go test -v
    - popd
    - cat lc.log
    - pushd messagebus/tests
    - go test -check.vv
    - popd


create_rpm:
  only:
    - tags
  stage: create_rpm
  script:
    - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
    - ls
    - pwd
    - bash package/rpmbuild.sh
    - echo $CI_COMMIT_TAG
    - create_release.sh  $CI_COMMIT_TAG  $CI_COMMIT_TAG
    - for i in `ls yig*.x86_64.rpm`; do echo $i; add_asset.sh $CI_COMMIT_TAG $i; s3cmd put $i s3://packages; done
    - ls

after_script:
  - pwd
  - ls
  - make clean
  - docker rm -f yig
  - docker rm -f lc
