package driver

import (
	"context"
	"io"
)

type StorageDriver interface {
	/* pool: ceph pool name
	* objectId: object id generated by yig.
	* meta: object storage meta.
	 */
	Write(ctx context.Context, pool string, objectId string, meta string, offset int64, data io.Reader) (int64, error)
	Read(ctx context.Context, pool string, objectId string, meta string, offset int64, length int64) (io.ReadCloser, error)
	Delete(ctx context.Context, pool string, objectId string, meta string, size int64) error
	GetUniqUploadName() string
	GetUsedSpacePercent() (int, error)
	GetName() string
}
