package driver

import "io"

type StorageDriver interface {
	/* pool: ceph pool name
	* objectId: object id generated by yig.
	* meta: object storage meta.
	 */
	Write(pool string, objectId string, meta string, offset int64, data io.Reader) error
	Read(pool string, objectId string, meta string, offset int64) (io.ReadCloser, error)
	Delete(pool string, objectId string, meta string, size int64) error
}
